sonar.projectKey=boinger_confvis
sonar.organization=boinger
sonar.projectName=confvis

sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**,**/*.md,badges/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
