// Package dashboard provides HTML dashboard generation for confidence reports.
package dashboard

import (
	"embed"
	"html/template"
	"io"
	"strings"

	"github.com/boinger/confvis/internal/confidence"
	"github.com/boinger/confvis/internal/gauge"
)

//go:embed templates/*.html
var templateFS embed.FS

// Options configures dashboard generation.
type Options struct {
	DarkMode bool
}

// MultiOptions configures multi-report dashboard generation.
type MultiOptions struct {
	DarkMode bool
	Fragment bool // Output content only, no HTML wrapper
}

// TemplateData holds data passed to the dashboard template.
type TemplateData struct {
	Report   *confidence.Report
	GaugeSVG template.HTML
	DarkMode bool
}

// ReportSummary holds a report with its weight and source path.
type ReportSummary struct {
	Report   *confidence.Report
	Weight   int
	Path     string
	GaugeSVG template.HTML
}

// MultiTemplateData holds data passed to the multi-dashboard template.
type MultiTemplateData struct {
	Reports      []ReportSummary
	Aggregate    *confidence.Report
	AggregateSVG template.HTML
	DarkMode     bool
}

// stripXMLDeclaration removes the XML processing instruction and SVGo comment
// from SVG output for inline HTML embedding.
func stripXMLDeclaration(svgStr string) string {
	svgStr = strings.Replace(svgStr, "<?xml version=\"1.0\"?>\n", "", 1)
	svgStr = strings.Replace(svgStr, "<!-- Generated by SVGo -->\n", "", 1)
	return svgStr
}

// Generate creates an HTML dashboard for the given report.
func Generate(w io.Writer, report *confidence.Report, opts Options) error {
	// Generate the gauge SVG (transparent for inline embedding)
	gaugeOpts := gauge.Options{
		ColorOptions:  gauge.ColorOptions{DarkMode: opts.DarkMode},
		Width:         200,
		Height:        120,
		TransparentBG: true,
	}
	gaugeSVG, err := gauge.GenerateToString(report, gaugeOpts)
	if err != nil {
		return err
	}

	// Parse and execute template (include base.html for shared styles)
	tmpl, err := template.ParseFS(templateFS, "templates/base.html", "templates/dashboard.html")
	if err != nil {
		return err
	}

	data := TemplateData{
		Report:   report,
		GaugeSVG: template.HTML(stripXMLDeclaration(gaugeSVG)), //#nosec G203 -- SVG generated internally by gauge package, not user input
		DarkMode: opts.DarkMode,
	}

	return tmpl.ExecuteTemplate(w, "dashboard.html", data)
}

// GenerateMulti creates an HTML dashboard for multiple reports with an aggregate view.
func GenerateMulti(w io.Writer, reports []ReportSummary, aggregate *confidence.Report, opts MultiOptions) error {
	// Generate gauge SVGs for each report (transparent for inline embedding)
	gaugeOpts := gauge.Options{
		ColorOptions:  gauge.ColorOptions{DarkMode: opts.DarkMode},
		Width:         200,
		Height:        120,
		TransparentBG: true,
	}

	for i := range reports {
		svgStr, err := gauge.GenerateToString(reports[i].Report, gaugeOpts)
		if err != nil {
			return err
		}
		reports[i].GaugeSVG = template.HTML(stripXMLDeclaration(svgStr)) //#nosec G203 -- SVG generated internally by gauge package, not user input
	}

	// Generate aggregate gauge
	aggregateSVG, err := gauge.GenerateToString(aggregate, gaugeOpts)
	if err != nil {
		return err
	}

	// Select template based on Fragment option
	templateName := "multi-dashboard.html"
	if opts.Fragment {
		templateName = "multi-dashboard-fragment.html"
	}

	// Parse and execute template (include base.html for shared styles)
	tmpl, err := template.ParseFS(templateFS, "templates/base.html", "templates/"+templateName)
	if err != nil {
		return err
	}

	data := MultiTemplateData{
		Reports:      reports,
		Aggregate:    aggregate,
		AggregateSVG: template.HTML(stripXMLDeclaration(aggregateSVG)), //#nosec G203 -- SVG generated internally by gauge package, not user input
		DarkMode:     opts.DarkMode,
	}

	return tmpl.ExecuteTemplate(w, templateName, data)
}
